config/routes.rb
Rails.application.routes.draw do
  resources :datos_estudiantes
  resources :users
  resources :estudiantes
  resources :buys
  root "datos_estudiantes#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/estudiante.rb
class Estudiante < ApplicationRecord
  validates_numericality_of :telefono
end

app/controllers/estudiantes_controller.rb
class EstudiantesController < ApplicationController
  before_action :set_estudiante, only: [:show, :edit, :update, :destroy]

  # GET /estudiantes
  # GET /estudiantes.json
  def index
    @estudiantes = Estudiante.all
  end

  # GET /estudiantes/1
  # GET /estudiantes/1.json
  def show
  end

  # GET /estudiantes/new
  def new
    @estudiante = Estudiante.new
  end

  # GET /estudiantes/1/edit
  def edit
  end

  # POST /estudiantes
  # POST /estudiantes.json
  def create
    @estudiante = Estudiante.new(estudiante_params)

    respond_to do |format|
      if @estudiante.save
        format.html { redirect_to @estudiante, notice: 'Estudiante was successfully created.' }
        format.json { render :show, status: :created, location: @estudiante }
      else
        format.html { render :new }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estudiantes/1
  # PATCH/PUT /estudiantes/1.json
  def update
    respond_to do |format|
      if @estudiante.update(estudiante_params)
        format.html { redirect_to @estudiante, notice: 'Estudiante was successfully updated.' }
        format.json { render :show, status: :ok, location: @estudiante }
      else
        format.html { render :edit }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estudiantes/1
  # DELETE /estudiantes/1.json
  def destroy
    @estudiante.destroy
    respond_to do |format|
      format.html { redirect_to estudiantes_url, notice: 'Estudiante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estudiante
      @estudiante = Estudiante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def estudiante_params
      params.require(:estudiante).permit(:nombres, :apellidos, :carrera, :carnet, :nacimiento, :telefono)
    end
end

app/helpers/estudiantes_helper.rb
module EstudiantesHelper
end

app/views/estudiantes/_form.html.erb
<%= form_with(model: estudiante, local: true) do |form| %>
  <% if estudiante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(estudiante.errors.count, "error") %> prohibited this estudiante from being saved:</h2>

      <ul>
      <% estudiante.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombres %>
    <%= form.text_field :nombres %>
  </div>

  <div class="field">
    <%= form.label :apellidos %>
    <%= form.text_field :apellidos %>
  </div>

  <div class="field">
    <%= form.label :carrera %>
    <%= form.text_field :carrera %>
  </div>

  <div class="field">
    <%= form.label :carnet %>
    <%= form.text_field :carnet %>
  </div>

  <div class="field">
    <%= form.label :nacimiento %>
    <%= form.date_select :nacimiento %>
  </div>

  <div class="field">
    <%= form.label :telefono %>
    <%= form.number_field :telefono %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/estudiantes/edit.html.erb
<h1>Editing Estudiante</h1>

<%= render 'form', estudiante: @estudiante %>

<%= link_to 'Show', @estudiante %> |
<%= link_to 'Back', estudiantes_path %>

app/views/estudiantes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Estudiantes</h1>

<table>
  <thead>
    <tr>
      <th>Nombres</th>
      <th>Apellidos</th>
      <th>Carrera</th>
      <th>Carnet</th>
      <th>Nacimiento</th>
      <th>Telefono</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estudiantes.each do |estudiante| %>
      <tr>
        <td><%= estudiante.nombres %></td>
        <td><%= estudiante.apellidos %></td>
        <td><%= estudiante.carrera %></td>
        <td><%= estudiante.carnet %></td>
        <td><%= estudiante.nacimiento %></td>
        <td><%= estudiante.telefono %></td>
        <td><%= link_to 'Show', estudiante %></td>
        <td><%= link_to 'Edit', edit_estudiante_path(estudiante) %></td>
        <td><%= link_to 'Destroy', estudiante, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Estudiante', new_estudiante_path %>

app/views/estudiantes/new.html.erb
<h1>New Estudiante</h1>

<%= render 'form', estudiante: @estudiante %>

<%= link_to 'Back', estudiantes_path %>

app/views/estudiantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombres:</strong>
  <%= @estudiante.nombres %>
</p>

<p>
  <strong>Apellidos:</strong>
  <%= @estudiante.apellidos %>
</p>

<p>
  <strong>Carrera:</strong>
  <%= @estudiante.carrera %>
</p>

<p>
  <strong>Carnet:</strong>
  <%= @estudiante.carnet %>
</p>

<p>
  <strong>Nacimiento:</strong>
  <%= @estudiante.nacimiento %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @estudiante.telefono %>
</p>

<%= link_to 'Edit', edit_estudiante_path(@estudiante) %> |
<%= link_to 'Back', estudiantes_path %>