config/routes.rb
Rails.application.routes.draw do
  resources :datos_estudiantes
  resources :users
  resources :estudiantes
  resources :buys
  root "datos_estudiantes#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/datos_estudiante.rb
class DatosEstudiante < ApplicationRecord

  validates_presence_of :nombres, :apellidos, :carnet, :carrera, presence: true
  validates_format_of :nombres, :apellidos, :carnet, :carrera, :with => /\A[a-zA-Z]+\z/

end

app/controllers/datos_estudiantes_controller.rb
class DatosEstudiantesController < ApplicationController
  before_action :set_datos_estudiante, only: [:show, :edit, :update, :destroy]

  # GET /datos_estudiantes
  # GET /datos_estudiantes.json
  def index
    @datos_estudiantes = DatosEstudiante.all
  end

  # GET /datos_estudiantes/1
  # GET /datos_estudiantes/1.json
  def show
  end

  # GET /datos_estudiantes/new
  def new
    @datos_estudiante = DatosEstudiante.new
  end

  # GET /datos_estudiantes/1/edit
  def edit
  end

  # POST /datos_estudiantes
  # POST /datos_estudiantes.json
  def create
    @datos_estudiante = DatosEstudiante.new(datos_estudiante_params)

    respond_to do |format|
      if @datos_estudiante.save
        format.html { redirect_to @datos_estudiante, notice: 'Datos estudiante was successfully created.' }
        format.json { render :show, status: :created, location: @datos_estudiante }
      else
        format.html { render :new }
        format.json { render json: @datos_estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /datos_estudiantes/1
  # PATCH/PUT /datos_estudiantes/1.json
  def update
    respond_to do |format|
      if @datos_estudiante.update(datos_estudiante_params)
        format.html { redirect_to @datos_estudiante, notice: 'Datos estudiante was successfully updated.' }
        format.json { render :show, status: :ok, location: @datos_estudiante }
      else
        format.html { render :edit }
        format.json { render json: @datos_estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /datos_estudiantes/1
  # DELETE /datos_estudiantes/1.json
  def destroy
    @datos_estudiante.destroy
    respond_to do |format|
      format.html { redirect_to datos_estudiantes_url, notice: 'Datos estudiante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_datos_estudiante
      @datos_estudiante = DatosEstudiante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def datos_estudiante_params
      params.require(:datos_estudiante).permit(:nombres, :apellidos, :carrera, :carnet)
    end
end

app/helpers/datos_estudiantes_helper.rb
module DatosEstudiantesHelper
end

app/views/datos_estudiantes/_form.html.erb
<%= form_with(model: datos_estudiante, class: 'mt-1 w-100', local: true) do |form| %>
  <% if datos_estudiante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(datos_estudiante.errors.count, "error") %> prohibited this datos_estudiante from being
        saved:</h2>

      <ul>
        <% datos_estudiante.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :nombres, for: 'name', class: 'font-weight-bold' %>
    <%= form.text_field :nombres, class: 'form-control', id: 'name' %>
  </div>

  <div class="form-group">
    <%= form.label :apellidos, for: 'last_name', class: 'font-weight-bold' %>
    <%= form.text_field :apellidos, class: 'form-control', id: 'last_name' %>
  </div>

  <div class="form-group">
    <%= form.label :carrera, for: 'carrera', class: 'font-weight-bold' %>
    <%= form.text_field :carrera, class: 'form-control', id: 'carrera' %>
  </div>

  <div class="form-group">
    <%= form.label :carnet, for: 'carnet', class: 'font-weight-bold' %>
    <%= form.text_field :carnet, class: 'form-control', id: 'carnet' %>
  </div>

  <div class="actions w-100 text-center">
    <%= link_to 'Back', datos_estudiantes_path, class: 'btn btn-link mr-5' %>
    <%= form.submit class: 'btn btn-primary text-white ml-5' %>
  </div>
<% end %>

app/views/datos_estudiantes/edit.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-12 w-100">
      <h1 class="display-4 font-weight-bold text-center">Editando Estudiante</h1>
    </div>

    <div class="mx-auto">
      <%= render 'form', datos_estudiante: @datos_estudiante %>
    </div>

  </div>
</div>

app/views/datos_estudiantes/index.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-12 w-100">
      <h1 class="display-4 font-weight-bold text-center">Estudiantes</h1>
    </div>

    <% if notice %>
      <div class="col-12 mt-2 w-100">
        <div class="alert alert-primary" role="alert">
          <%= notice %>
        </div>
      </div>
    <% end %>

    <%= link_to 'Nuevo estudiante', new_datos_estudiante_path, class: 'btn btn-primary text-white mt-5' %>

    <table class="table mt-5">
      <thead>
      <tr>
        <th scope="col">Nombres</th>
        <th scope="col">Apellidos</th>
        <th scope="col">Carrera</th>
        <th scope="col">Carnet</th>
        <th scope="col">Acciones</th>
      </tr>
      </thead>
      <tbody>
      <% @datos_estudiantes.each do |datos_estudiante| %>
        <tr>
          <td style="font-size: 16px;"><%= datos_estudiante.nombres %></td>
          <td style="font-size: 16px;"><%= datos_estudiante.apellidos %></td>
          <td style="font-size: 16px;"><%= datos_estudiante.carrera %></td>
          <td style="font-size: 16px;"><%= datos_estudiante.carnet %></td>
          <td>
            <%= link_to 'Mostrar detalles', datos_estudiante, class: 'btn btn-primary text-white' %>
            <%= link_to 'Editar', edit_datos_estudiante_path(datos_estudiante), class: 'btn btn-warning text-white' %>
            <%= link_to 'Eliminar', datos_estudiante, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-danger text-white' %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/datos_estudiantes/new.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-12 w-100">
      <h1 class="display-4 font-weight-bold text-center">Nuevo Estudiante</h1>
    </div>

    <div class="mx-auto">
      <%= render 'form', datos_estudiante: @datos_estudiante %>
    </div>

  </div>
</div>

app/views/datos_estudiantes/show.html.erb
<div class="container">
  <div class="row mt-5">
    <div class="col-12 w-100">
      <h1 class="display-4 font-weight-bold text-center">
        <%= @datos_estudiante.nombres %> <%= @datos_estudiante.apellidos %>
      </h1>
    </div>

    <% if notice %>
      <div class="col-12 mt-2 w-100">
        <div class="alert alert-primary" role="alert">
          <%= notice %>
        </div>
      </div>
    <% end %>

    <table class="table mt-5" style="text-align: center">
      <thead>
      <tr>
        <th scope="col">Nombres</th>
        <th scope="col">Apellidos</th>
        <th scope="col">Carrera</th>
        <th scope="col">Carnet</th>
      </tr>
      </thead>
      <tbody>
      <tr>
        <td style="font-size: 16px;"><%= @datos_estudiante.nombres %></td>
        <td style="font-size: 16px;"><%= @datos_estudiante.apellidos %></td>
        <td style="font-size: 16px;"><%= @datos_estudiante.carrera %></td>
        <td style="font-size: 16px;"><%= @datos_estudiante.carnet %></td>
      </tr>
      </tbody>
    </table>

    <div class="mx-auto w-100 text-center">
      <%= link_to 'Regresar', datos_estudiantes_path, class: 'btn btn-link mt-5 mr-5' %>
      <%= link_to 'Editar usuario', edit_datos_estudiante_path(@datos_estudiante), class: 'btn btn-primary text-white mt-5' %>
    </div>
  </div>
</div>