config/routes.rb
Rails.application.routes.draw do
  resources :datos_estudiantes
  resources :users
  resources :estudiantes
  resources :buys
  root "datos_estudiantes#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/buy.rb
class Buy < ApplicationRecord
  validates :category, :description, :amount, presence: true
end

app/controllers/buys_controller.rb
class BuysController < ApplicationController
  before_action :set_buy, only: [:show, :edit, :update, :destroy]

  # GET /buys
  # GET /buys.json
  def index
    @buys = Buy.all
  end

  # GET /buys/1
  # GET /buys/1.json
  def show
  end

  # GET /buys/new
  def new
    @buy = Buy.new
  end

  # GET /buys/1/edit
  def edit
  end

  # POST /buys
  # POST /buys.json
  def create
    @buy = Buy.new(buy_params)

    respond_to do |format|
      if @buy.save
        format.html { redirect_to @buy, notice: 'Buy was successfully created.' }
        format.json { render :show, status: :created, location: @buy }
      else
        format.html { render :new }
        format.json { render json: @buy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buys/1
  # PATCH/PUT /buys/1.json
  def update
    respond_to do |format|
      if @buy.update(buy_params)
        format.html { redirect_to @buy, notice: 'Buy was successfully updated.' }
        format.json { render :show, status: :ok, location: @buy }
      else
        format.html { render :edit }
        format.json { render json: @buy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buys/1
  # DELETE /buys/1.json
  def destroy
    @buy.destroy
    respond_to do |format|
      format.html { redirect_to buys_url, notice: 'Buy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buy
      @buy = Buy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buy_params
      params.require(:buy).permit(:category, :description, :amount)
    end
end

app/helpers/buys_helper.rb
module BuysHelper
end

app/views/buys/_form.html.erb
<%= form_with(model: buy, local: true) do |form| %>
  <% if buy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(buy.errors.count, "error") %> prohibited this buy from being saved:</h2>

      <ul>
      <% buy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :amount %>
    <%= form.text_field :amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/buys/edit.html.erb
<h1>Editing Buy</h1>

<%= render 'form', buy: @buy %>

<%= link_to 'Show', @buy %> |
<%= link_to 'Back', buys_path %>

app/views/buys/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Buys</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Description</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buys.each do |buy| %>
      <tr>
        <td><%= buy.category %></td>
        <td><%= buy.description %></td>
        <td><%= buy.amount %></td>
        <td><%= link_to 'Show', buy %></td>
        <td><%= link_to 'Edit', edit_buy_path(buy) %></td>
        <td><%= link_to 'Destroy', buy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Buy', new_buy_path %>

app/views/buys/new.html.erb
<h1>New Buy</h1>

<%= render 'form', buy: @buy %>

<%= link_to 'Back', buys_path %>

app/views/buys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @buy.category %>
</p>

<p>
  <strong>Description:</strong>
  <%= @buy.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @buy.amount %>
</p>

<%= link_to 'Edit', edit_buy_path(@buy) %> |
<%= link_to 'Back', buys_path %>